### ISSUE TITLE
Disable preset

### ISSUE THREAD

**Issue by pixeldesbois** [jmcollin78/versatile-thermostat-ui-card#11]
Hello,

Is it possible to disable preset if the corresponding temperature equal 0 (desactivated) ?

Thank you

**Comment by jmcollin78** [comment]
Preset is the heart of Versatile Thermostat. Are you sure you don't want to use presets ?

**Comment by pixeldesbois** [comment]
Bonjour
Je vais poursuivre en français si tu le veux bien. Cela sera plus simple pour expliquer.
Pour chaque thermostat, on a la possibilité de paramétrer les températures pour les preset pour Eco, Confort et Boost.
Si on souhaite en ignorer un (boost par exemple), on met 0 comme valeur de température.

SI on a mis 0, ca serait si au niveau de la card, le preset soit masqué.
En espérant avoir été plus clair dans mes explications.

**Comment by jmcollin78** [comment]
J'avais bien compris. Mais ma question c'était de savoir alors qu'il n'y a que 3 presets et que le fonctionnement en preset est au coeur de Versatile Thermostat, pourquoi tu voudrais en désactiver certains ?

La plupart du temps on me demande l'inverse : je voudrais un preset de plus pour ceci ou pour cela.

Tu m'as surpris et je curieux de savoir comment tu utilises le VTherm du coup.

**Comment by pixeldesbois** [comment]
J'utilise le boost uniquement pour la salle de bain. Avec une automatisation je le coupe au bout d'une heure.
Les autres pièces, je ne me sers que d'Eco et Confort. Je joue sur la présence/absence et le scheduler pour affiner.
Exemple pour une piece :
- Presence : Eco 19 /Confort 20
- Absence : Eco 17 /Confort 19

Scheduler : 
- de minuit à 6h : ECO
- 6 à 8h : Confort
- 8 à 16: Eco
- 16 à 22 Confort

Ma femme et les enfants arrivent vers 17h. Donc la piece est à 17° jusque 16h puis passe à 19° jusque à la détection de présence qui bascule à 20°. 

On pourrait imaginer jouer avec le mode Boost pour accelerer la transition absence vers présence... je garde cela dans un coin de la tête.

**Comment by jmcollin78** [comment]
I just have a look and it is not possible simply:
1. the card doesn't have access to the temperature values but only to the list of presets which comes from backend,
2. the same preset can have multiple values (one set of values with AC mode, one set of values with presence Away, ...). So it can be 0 for one set but not for the other.

So it is not a front end behavior but more a backend feature and I will implement this: https://github.com/jmcollin78/versatile_thermostat/issues/248

**Comment by tomtom13** [comment]
Yeah, all great but that doesn't work. If you set allowed range to be 10-30 (so users don't set stupid low temp) you can't set zero in central control form presets. I'm honestly surprised why range check is forced for configuring back end.
