### ISSUE TITLE
Repository structure for 0.4.0 is not compliant

### ISSUE THREAD

**Issue by maximegy** [jmcollin78/versatile-thermostat-ui-card#12]
Hello,
I have a problem when I want to add the depot to HACS.
The error is "Repository structure for 0.4.0 is not compliant"
![image](https://github.com/jmcollin78/versatile-thermostat-ui-card/assets/18288976/8a40f09b-ac6e-4aa5-95ed-d555a4f17e32)
Can you help ?
Thanks a lot.

**Comment by dcjona** [comment]
same here ...

**Comment by DavidGeorge528** [comment]
Category should be `Lovelace` not `Integration`

**Comment by maximegy** [comment]
Hello,
The problem occurs for both intégration and lovelace.
Thanks

**Comment by maximegy** [comment]
You must be right, the argument "it works on my pc so it must works on yours" always work...

But the reality is that it doesn't work for me and another user.
![image](https://github.com/jmcollin78/versatile-thermostat-ui-card/assets/18288976/c70ba8cf-ba80-4fcd-a2eb-02c90f682ae4)

Home assistant OS.
![image](https://github.com/jmcollin78/versatile-thermostat-ui-card/assets/18288976/4cf89edb-2da2-48a9-8011-3b183631389c)

It appears that an update has changed the expected structure for the installation.

Thanks for your help
