### ISSUE TITLE
[Bug] Alignment of card changes as button rows are hidden

### ISSUE THREAD

**Issue by DavidGeorge528** [jmcollin78/versatile-thermostat-ui-card#16]
It seems that the title and temperature bar are aligned differently to the temperature text and buttons that appear within the arc of the temperature bar. As a result hiding all buttons in a row (i.e. all HVAC modes) changes the alignment of the text within the temperature arc. See below:

![image](https://github.com/jmcollin78/versatile-thermostat-ui-card/assets/7761453/d65acee0-f4d3-4421-becc-6bc85bbf84e2)

This problem is made even worse if you use a non-Versatile thermostat, which results in the preset buttons being hidden (see below). I also imagine this causes the row of sensor icons (motion, window, etc) to clip the temperature arc.

![image](https://github.com/jmcollin78/versatile-thermostat-ui-card/assets/7761453/11395c38-87b8-4049-b631-21d453408c1a)

Edit, added photo of thermostat with no buttons to show the text shifted all the way up

**Comment by jmcollin78** [comment]
That is possible but having no havc_mode is weird. This should not possible. You should always be able to turn-off and turn-on with heat or cool.

**Comment by jmcollin78** [comment]
ok. Turning off an HVAC controlled by VTherm without turning off on VTherm it self is strange but wht not it is working like that.

I will try to have a look but I'm really not a UI expert... Will try to do my best.

**Comment by DavidGeorge528** [comment]
Unless I missed something in the setup, the VTherm thermostats controlling my TRVs don't have an `off` `hvac` option. Is there a way of making a virtual `off` action?

**Comment by jmcollin78** [comment]
The hvac_,modes of the VTherm in over_climate mode is the ones of the underlying.
