### ISSUE TITLE
Icone et fonction absente

### ISSUE THREAD

**Issue by Egainmoney** [jmcollin78/versatile-thermostat-ui-card#2]
Salut sur le menu de l'interface certain bouton n'apparaisse pas .

Désactiver fenêtre status ; n'apparais pas  malgrés le statut ok dans la configuration et les tests arrêt que j'ai fait sur la clim.

Désactiver mode clim : ? je vois pas encors le but ;) mais je presume que l'icone de cool devrais disparaitre ?

Désactiver sur-puissance status n'apparais pas mais sur une clim je suis pas sur qu'il doit apparaitre ?
Désactiver sécurité messages pareille ou cela doit apparaitre ?

sinon ca rend le climate plus joile a gerer bravo

**Comment by jmcollin78** [comment]
Quel type de VTherm tu as ?

**Comment by Egainmoney** [comment]
Salut j'ai tester sur mes deux vtherm climatisation à la mise en place de
la version 4 sortie hier puis sur le vtherm convecteur de ma fille qui gère
aussi l'ouverture de fenêtres je te fait un screen ce midi en rentrant du
boulot

Le mar. 7 nov. 2023, 01:12, Jean-Marc Collin ***@***.***> a
écrit :

**Comment by jmcollin78** [comment]
Je crois que tu n'as pas compris comment c'est censé fonctionner. C'est pas étonnant puisqu'il n'y a pas beaucoup de doc. J'ai juste mlis à jour celle du Better Thermostat UI qui m'a servi de source.

Les options "desactiver ..." permettent de masquer les états remontés par le VTherm mais ne supprime pas les états.

Le VTherm calcule des états et le VTherm UI Card les affichent ou non (mais ils de toutes façons toujours calculés).

> Désactiver fenêtre status

Ca permet de ne pas afficher l'icone fenêtre ouverte dans l'UI lorsqu'elle est détectée par le VTherm,

> Désactiver mode clim

Pour les clims réversibles ou bi-mode ça permet de masquer le mode clim.

> Désactiver sur-puissance status

Pareil avec l'indicateur de sur-puissance. Ca fonctionne aussi sur les VTherm over_climate si tu l'as configuré correctement (un capteur de mesure de la puissance installée, un capteur donnant le max et la puissance de l'équipement).

**Comment by jmcollin78** [comment]
Est-ce que c'est ok pour toi maintenant ?

**Comment by Egainmoney** [comment]
Salut oui je ferme ce ticket

**Comment by Egainmoney** [comment]
salut oui je ferme ce ticket
