### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by daxter62** [jmcollin78/versatile-thermostat-ui-card#20]
Hello maybe I haven't got the good process but when I want to install the report,
I have this error :
<Integration jmcollin78/versatile-thermostat-ui-card> Repository structure for 0.5.0 is not compliant

Thx

**Comment by jmcollin78** [comment]
I guess you have succeeded now. You are certainly not in the right place to add the repo. You should go to "Interface" section of HACS.
