### ISSUE TITLE
Incrément par pas de 0.5

### ISSUE THREAD

**Issue by stephanehouse** [jmcollin78/versatile-thermostat-ui-card#23]
Bonjour, je ne vois pas ou trouver l'option qui permet de modifier l'incrément de température des thermostats. Elle est de 0.1°C par défaut, je voudrai la modifier à 0.5, j'ai bien lu le post ou vous avez noté "default temperature step" mais je ne sais pas ou chercher cette option modifiable, est-elle toujours implémentée ?

Merci :)

**Comment by jmcollin78** [comment]
Hello, je ne l'ai pas fait et ce sera fait coté serveur (sur le Versatile Thermostat): https://github.com/jmcollin78/versatile_thermostat/issues/311

Ce que j'ai fait c'est que si le step coté serveur n'est pas fourni, il est par défaut à 0,5 mais il est fourni la carte prend le step coté serveur.
