### ISSUE TITLE
Repository structure for 0.5.0 is not compliant

### ISSUE THREAD

**Issue by gdesmott** [jmcollin78/versatile-thermostat-ui-card#28]
I'm getting this error when trying to add the repo in HACS 1.34.0 with HA 2024.2.4 :

![image](https://github.com/jmcollin78/versatile-thermostat-ui-card/assets/1379524/767f914f-eaa2-41ce-8606-f6c84bc0a516)

**Comment by jmcollin78** [comment]
This is not an integration but a UI card.
