### ISSUE TITLE
Card does not appear in lovelace selection

### ISSUE THREAD

**Issue by marcbaro** [jmcollin78/versatile-thermostat-ui-card#29]
After installing the card through hacs, it doesn't appear when I try to add it to lovelace panel. Even if I try to manually configure, I receive the error: 'Custom element doesn't exist: versatile-thermostat-ui-card'.
The folder 'versatile-thermostat-ui-card' with two files exists in 'www/community'

HA core: 2024.2.5
HA OS: 12.0

**Comment by Stef33fr** [comment]
I have the same issue

**Comment by anthony-lepors** [comment]
Same

**Comment by jmcollin78** [comment]
Hello, if the card is correctly installed with HACS, it is visible on my side:
![Capture d’écran 2024-08-31 à 08 20 59](https://github.com/user-attachments/assets/2709a07e-2590-44bd-9275-ad03166b38ad)
