### ISSUE TITLE
Bug over power

### ISSUE THREAD

**Issue by gael1980** [jmcollin78/versatile-thermostat-ui-card#3]
Bonjour,

Encore bravo pour le thermostat que j'utilise depuis le début et maintenant la carte. 

Concernant la carte, j'ai un bug d'affichage : le symbole ower power ne s'affiche pas dans la carte du thermostat.
Comme tu peux le voir sur l'image, elle est pourtant activée par le thermostat.

En bas à droite, j'ai rajouté une carte pour me le confirmer. Et la température est bien celle configurée en cas de dépassement.

<img width="1178" alt="Capture d’écran 2023-11-08 à 07 00 46" src="https://github.com/jmcollin78/versatile-thermostat-ui-card/assets/35664315/0974ba1b-db99-488b-adfa-06a30938ce03">

J'utilise la version 0.2 de la carte et 4.0.1 du thermostat.
Dans la config de la carte, je n'ai désactivé que la clim.

Merci.

Gaël

**Comment by jmcollin78** [comment]
Je te confirme avoir vu le soucis aussi.
