### ISSUE TITLE
Carte estompée

### ISSUE THREAD

**Issue by AlBla84140** [jmcollin78/versatile-thermostat-ui-card#30]
Bonjour Jean-Marc,
Pourquoi ma carte devient-elle estompée avec des messages "Room temp. : 51 min" et "External temp. : 54 min".
La carte n'est plus accessible aux modifications.
Merci.

**Comment by jmcollin78** [comment]
Bonjour,

Il s'agit de la fonction de sécurité lorsqu'un thermomètre n'a pas donné de valeur depuis longtemps.

Cf. https://github.com/jmcollin78/versatile_thermostat/blob/main/README-fr.md#pourquoi-mon-versatile-thermostat-se-met-en-securite-
