### ISSUE TITLE
Add radial-gradien color around the main temperature number

### ISSUE THREAD

**Issue by jmcollin78** [jmcollin78/versatile-thermostat-ui-card#33]
As a end user,
When i remove the colored circle on the VTherm,
I need to quickly see what the hvac_mode of the VTherm.

Before the circle was colored with the hvac_mode so it was easy to see the hvac_mode. Now you just have the hvac_mode button displayed and it is not very easy to see in whatr mode you are especially if this button are masked.

**Comment by NicoBerlo1** [comment]
Hi !
Could we please have a preference to disable the display of the gradient color ?
Otherwise, the new display is great :)
thanks !

**Comment by jmcollin78** [comment]
Hi, 

Don't you like my radial color ? 🥹 

Could you please open a new issue ? I should have close this one because it is already released in 1.0.0.


Thank you

**Comment by NicoBerlo1** [comment]
Disons que j'aime bien le look plus épuré :)
