### ISSUE TITLE
Add option to specify temperature increment for manual temperature settings [feature request]

### ISSUE THREAD

**Issue by mleiber** [jmcollin78/versatile-thermostat-ui-card#4]
Add a configuration option to specify the temperature increment when changing the temperature manually via the the plus/minus buttons or the slider.

Currently it is +/- one degree only, should be allowed to be more fine grained, e.g. 0.5 or even 0.2 degrees or whatever the user desires.

**Comment by jmcollin78** [comment]
I will use the default increment coming from Thermostat. But there is a bug in VTherm so I have to republish it before you can have a try.

**Comment by mleiber** [comment]
I assume you mean the 'precision' attribute of the climate entity, right ?
That would most certainly fit the purpose. If I checked correctly that
attribute would need to be exposed first - doesn't seem it's in your
current implementation of the versatile thermostat.

Thanks for responding so quickly to requests. Appreciated.

Am So., 12. Nov. 2023 um 12:30 Uhr schrieb Jean-Marc Collin <
***@***.***>:

**Comment by jmcollin78** [comment]
Yes. You have to wait for the next release that was my purpose.

**Comment by YannickF** [comment]
Hello
Last release gives 0.1 °C steps.... but where is it configurable ?

**Comment by jmcollin78** [comment]
It is the default temperature step of the VTherm. On an over_climate it is the default step of the underlying climate
